apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: mysql
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}