apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.ports.postgresql }}
      targetPort: 5432